### ISSUE TITLE
How to run from within a module?

### ISSUE THREAD

**Issue by verdverm** [1pkg/gopium#19]
When running `gopium` from within a module, it still looks for the source within the `$GOROOT/src` directory. Is there a way to run this from within a module's directory, when outside of the `$GOROOT/src` directory?

**Comment by 1pkg** [comment]
@verdverm indeed there were problems with modules before but it was solved in v1.2.0; try to use latest gopium v1.2.5 it should work as expected.

For e.g. on my local machine (as you can tell `/Users/default/Downloads/gopium/walkers` is package outside of my gopath).

![image](https://user-images.githubusercontent.com/33581864/101619274-57fe3800-3a13-11eb-9256-b4b8aeb55834.png)

**Comment by 1pkg** [comment]
will consider this fixed then
