### ISSUE TITLE
How to disable Output tab to open itself on each click?

### ISSUE THREAD

**Issue by frederikhors** [1pkg/gopium#25]
Using your amazing gopium I have each time opened the OUTPUT tab. Can we disable this behavior?

**Comment by 1pkg** [comment]
I will take a look on what could be done with this vscode behavior.

**Comment by 1pkg** [comment]
The issue should be resolved by https://github.com/1pkg/gopium/pull/27.
I added a new option `showConsole` to the extension settings (by default the tab no longer will be shown).
